databricks:
  catalog: your_catalog
  schema: your_schema
  model: your_agent_name
  workspace_url: https://your-workspace.databricks.com  # Your Databricks workspace URL (required for UC Connection)
  sql_warehouse_id: your_sql_warehouse-id
  mlflow_experiment_id: your_mlflow_experiment_id
  databricks_pat:
    secret_scope_name: your_secret_scope
    secret_key_name: your_secret_key_name

tools:
  uc_connection:
    name: connection_name
  tables:
    - your_catalog.your_schema.table1
    - your_catalog.your_schema.table2
  uc_functions:
    - get_table_metadata
    - get_table_schema
    - get_sample_data
    - validate_query
    - execute_query

agent:
  llm:
    endpoint: databricks-claude-sonnet-4-5
    temperature: 0.1
  max_iterations: 10  # Maximum number of tool calling iterations before stopping
  system_prompt_path: ../../system_prompt.md
  